version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20
    working_directory: ~/app

jobs:
  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Vercel CLI
          command: npm install -g vercel
      - run:
          name: Deploy to Vercel
          command: |
            vercel --prod \
              --token $VERCEL_TOKEN \
              --yes \
              --scope $VERCEL_ORG_ID \

workflows:
  deploy-on-main:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
